grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

prometheus:
  service:
    type: ClusterIP

alertmanager:
  service:
    type: ClusterIP