apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudflared
  namespace: cloudflare

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloudflared

  template:
    metadata:
      labels:
        app: cloudflared

    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest

          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config/config.yaml
            - run

          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token

          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 200m
              memory: 256Mi

      volumes:
        - name: cloudflared-config
          configMap:
            name: cloudflared-config

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudflared-config
  namespace: cloudflare

data:
  config.yaml: |
    ingress:
      - hostname: argocd.xambook.com
        service: http://argocd-server.argocd.svc.cluster.local:80

      - hostname: api.xambook.com
        service: http://xambook-backend.default.svc.cluster.local:8080

      - hostname: xambook.com
        service: http://xambook-frontend.default.svc.cluster.local:80

      - hostname: www.xambook.com
        service: http://xambook-frontend.default.svc.cluster.local:80

      - service: http_status:404