apiVersion: apps/v1
kind: Deployment

metadata:
  name: xambook-backend
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: xambook-backend

  template:
    metadata:
      labels:
        app: xambook-backend

    spec:
      containers:
        - name: backend
          image: harishsudalaimani/xambook-backend:e5a202791367e5437251091a7c32605093ca8303

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_URL

            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: razorpay-secret
                  key: RAZORPAY_KEY_ID

            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: razorpay-secret
                  key: RAZORPAY_KEY_SECRET

            - name: PORT
              value: "8080"

            - name: MINIO_ENDPOINT
              value: minio.storage.svc.cluster.local:9000

            - name: MINIO_ACCESS_KEY
              value: admin

            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"