apiVersion: apps/v1
kind: Deployment
metadata:
  name: xambook-backend
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: xambook-backend

  template:
    metadata:
      labels:
        app: xambook-backend

    spec:
      containers:
        - name: backend
          image: harishsudalaimani/xambook-backend:fbba3e18c1dabe9c8569854f57a77833b9a3d75c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: POSTGRES_URL
            value: postgres://postgres:postgres123@postgres:5432/xambook?sslmode=disable
          - name: RAZORPAY_KEY_ID
            value: your_key
          - name: RAZORPAY_KEY_SECRET
            value: your_secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"