FROM golang:1.25 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o importer ./cmd/importer
FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/importer .
CMD ["./importer"]