apiVersion: apps/v1
kind: Deployment
metadata:
  name: xambook-frontend
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: xambook-frontend

  template:
    metadata:
      labels:
        app: xambook-frontend

    spec:
      containers:
        - name: frontend

          image: harishsudalaimani/xambook-frontend:1610dd394236bbc91879c4caf6dfc95f7ab434c7

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"