apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: minio
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0

    helm:
      values: |
        mode: standalone

        rootUser: admin
        rootPassword: CHANGE_THIS_PASSWORD

        persistence:
          enabled: false

        resources:
          requests:
            memory: 256Mi

        service:
          type: ClusterIP

        consoleService:
          type: ClusterIP

        minioConsole:
          enabled: true

        extraEnvVars:
          - name: MINIO_BROWSER_REDIRECT_URL
            value: https://console.xambook.com

  destination:
    server: https://kubernetes.default.svc
    namespace: storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true