
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-user
  namespace: minio
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER=xambook
    export MINIO_ROOT_PASSWORD=xambook2025secure