apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: xambook-minio
  namespace: minio
spec:
  image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  configuration:
    name: minio-root-user
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      env:
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://console.minio.xambook.com
        - name: MINIO_SERVER_URL
          value: https://minio.xambook.com
      volumeClaimTemplate:
        metadata:
          name: minio-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      resources:
        requests:
          memory: 256Mi
          cpu: "100m"
        limits:
          memory: 512Mi
          cpu: "500m"
      nodeSelector:
        role: data
  mountPath: /export
  requestAutoCert: false
  features:
    bucketDNS: false