apiVersion: batch/v1
kind: Job

metadata:
  name: question-import
  namespace: default

spec:
  template:
    spec:
      containers:
        - name: importer
          image: harishsudalaimani/xambook-importer:be423ab8c477c3b9828c2bb3f8a4e6b0f8a6505a

          env:
            - name: POSTGRES_URL
              value: postgres://postgres:postgres123@postgres:5432/xambook?sslmode=disable

      restartPolicy: Never

  backoffLimit: 1