apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xambook-tls
  namespace: xambook
spec:
  secretName: xambook-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - xambook.com
    - gcp.xambook.com
    - www.xambook.com
    - argocd.xambook.com
    - minio.xambook.com
    - console.minio.xambook.com