apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: xambook-gateway
  namespace: xambook
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: xambook-tls-secret
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: xambook-http-redirect
  namespace: xambook
spec:
  parentRefs:
    - name: xambook-gateway
      sectionName: http
  hostnames:
    - "xambook.com"
    - "gcp.xambook.com"
    - "www.xambook.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: xambook-routes
  namespace: xambook
spec:
  parentRefs:
    - name: xambook-gateway
      sectionName: https
  hostnames:
    - "xambook.com"
    - "gcp.xambook.com"
    - "www.xambook.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80