apiVersion: batch/v1
kind: Job

metadata:
  name: question-import
  namespace: default

spec:
  template:
    spec:
      containers:
        - name: importer
          image: harishsudalaimani/xambook-importer:c24217d5ecdcfa86bf4cddc59b8b7ba80c7eb829

          env:
            - name: POSTGRES_URL
              value: postgres://postgres:postgres123@postgres:5432/xambook?sslmode=disable

      restartPolicy: Never

  backoffLimit: 1