apiVersion: batch/v1
kind: Job
metadata:
  name: question-import
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: importer
          image: harishsudalaimani/xambook-importer:6184a81ee47f23297c4dbd9fb94b0ee22db0623f
          env:
            - name: POSTGRES_URL
              value: postgres://postgres:postgres123@postgres:5432/xambook?sslmode=disable
      restartPolicy: Never
  backoffLimit: 1