apiVersion: batch/v1
kind: Job
metadata:
  name: question-import
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: importer
          image: harishsudalaimani/xambook-importer:4b44022b8bf44ed2479993737a041ba13bde5fe9
          env:
            - name: POSTGRES_URL
              value: postgres://postgres:postgres123@postgres:5432/xambook?sslmode=disable
      restartPolicy: Never
  backoffLimit: 1