apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host        # 3 hosts => one replica per node
  replicated:
    size: 3                  # tolerate losing 1 node with data still readable/writable
    requireSafeReplicaSize: true
